version: '3.7'

services:
  frontend:
    container_name: ngflix-dev_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
